# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      PYTHONPATH: src 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 pytest transformers kaggle
        pip install --index-url https://download.pytorch.org/whl/cpu torch==2.7.1

    - name: Configure Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        printf '{"username":"%s","key":"%s"}' "$KAGGLE_USERNAME" "$KAGGLE_KEY" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json


    - name: Train model
      run: python src/model_trainer.py
      timeout-minutes: 60

    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
        retention-days: 20

    - name: Push to Hugging Face Hub
      #Esegue questo step solo se il token HF Ã¨ disponibile e siamo sul branch main
      if: github.ref == 'refs/heads/main' && env.KAGGLE_KEY != ''
      run: |
        huggingface-cli login --token $KAGGLE_KEY
        huggingface-cli upload \
          $KAGGLE_USERNAME/sentiment-analysis-profAI \
          models/ \
          . \
          --repo-type model \
          --commit-message "Push del modello addestrato dalla CI "
    - name: Test with pytest
      working-directory: "tests"
      run: pytest